backend:
  name      : github
  repo      : gaou-piou/Jetdrops
  branch    : master
media_folder: "images/uploads"
collections:
  - name: "general"
    label: "Site Settings"
    file: "site/_data/settings.json"
    extension: "json"
    description: "General Site Settings"
    fields:
        - {label: "Global title", name: "site_title", widget: "string"}
        - label: "Post Settings"
          name: "posts"
          widget: "object"
          fields:
              - {label: "Number of posts on frontpage", name: front_limit, widget: number}
              - {label: "Default Author", name: author, widget: string}
              - {label: "Default Thumbnail", name: thumb, widget: image, class: "thumb"}