backend:
  name      : github
  repo      : gaou-piou/Jetdrops
  branch    : master
media_folder: "images/uploads"
collections:
  -
    label: "Settings"
    name: "settings"
    files:
      -
        label: "Site Settings"
        name: "general"
        file: "site/_data/settings.yml"
        fields:
          -
            {label: "Site title", name: "site_title", widget: "string"}